version: '3.9'

services:
  app:
    build: ./build
    container_name: bookmedik
    image: joseantonio093/bookmedik:v1
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - frontend-network
      - backend-network

  db:
    container_name: servidor_mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend-network

volumes:
    mariadb_data:

networks:
    frontend-network:
    backend-network:
